### ISSUE TITLE
MSCLoader not Updating

### ISSUE THREAD

**Issue by Squizzy2k** [piotrulos/MSCModLoader#171] opened 2023-07-20 08:52 UTC
### OS version/build

Win 10

### MSCLoader version

1.2.12

### Description

When to start the game
and the MSCLOader is displaying the following
MSCLoader v1.2.12 ready green
Error Check for new version failed with error: Error: NameResolutionFailure
Loaded 10 Mods

Error: Failed to check for mods updates
Error: Error:NameResolutionFailure

Was working for the fast 2 week
I did install Jack and triangle mod which was for MSCLoader Pro (which I didn't realize until after the install, which stopped the update at 50% and gave errors
Tried to remove the 2 files and tried again but was stuck at the 50% updating

So I uninstalled the game and reinstalled
Installed MSCLoader 
and placed now just the files that did work before and not the Jack and Triangle
But now still not working as Shown above  :(

I'm kinda lost as to what to do next
Thanks
![Error2](https://github.com/piotrulos/MSCModLoader/assets/140057435/07f95cd7-87a2-4b5a-8d1b-96508e8ca60c)
![Error1](https://github.com/piotrulos/MSCModLoader/assets/140057435/bb9850c7-7f58-40e2-9b2e-b3939db87044)
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/12104035/output_log.txt)
[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/12104039/MSCLoader_Preloader.txt)

### Attachments

[MSCLoader_Preloader.txt](https://github.com/piotrulos/MSCModLoader/files/12104043/MSCLoader_Preloader.txt)
[output_log.txt](https://github.com/piotrulos/MSCModLoader/files/12104044/output_log.txt)

**Comment by ThexGameLord** [comment] 2023-07-20 09:04
The problem is that the **my-summer-car.ml** domain is unable to be resolved from dns servers so the update part of the mscloader doesn't know where to get the updates from, as it sends http requests to the server and checks for the **version, authorization, references, etc**
 i recently checked this with wireshark, we will wait a bit until the domain is able to be resolved. 👍🏾

**Comment by piotrulos** [comment] 2023-07-20 10:10
it happens with free domains. Also seems like it's just partial outdage since there are still normal traffic for update server, from many places. So it's probably on whatever dns servers you using.

**Comment by piotrulos** [comment] 2023-07-21 18:24
Well .ml domains are dead, I got new domain so it's fixed in 1.2.13 update

**Closed by piotrulos** 2023-07-21 18:24 UTC
Labels: bug
